import Head from 'next/head';
import conectarDB from '../lib/dbConnect';
import Anime from '../models/Anime';
import Link from 'next/link';

export default function Home({animes}) {
    console.log(animes);
  return (
    <div>
      <Head>
        <title>CRUD en Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section className="py-5 text-center container">
          <div className="row py-lg-5">
            <div className="col-lg-6 col-md-8 mx-auto">
              <h1 className="fw-light">Anime List<span className="ai-list"></span></h1>
              <p className="lead text-body-secondary">Actividad integradora de la unidad 2. Ejercicio de CRUD en NEXT.</p>
              <p>
                <a href="/new" className="btn btn-primary my-2">Agregar</a>
              </p>
              {animes.map(({ _id, title, plot }) => (
                <div className='card mb-2' key={_id}>
                  <div className='card-body'>
                    <div className='h5 text-uppercase'>{title}</div>
                    <p className='fw-light'>{plot}</p>
                    <Link className="btn btn-success btn-sm" href={`/${_id}`}>Ver detalle</Link>
                    
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

// Conexión a la base de datos.
export async function getServerSideProps() {
  try {
    await conectarDB();

    const res = await Anime.find({});

    const animes = res.map((doc) => {
      const Anime = doc.toObject();
      Anime._id = `${Anime._id}`;
      return Anime;
    });

    return {props: {animes}};
  } catch (error) {
    console.log (error);
    return { props: { success: false, error: '¡Error! D:,'}};
  }
}
